### ISSUE TITLE
as a Tester you are not allowed to touch REQUIREMENTS

### ISSUE THREAD

**Issue by sebiboga** [eszteradorjani/QA-certification-project#1]
We as software testers are testing an application based on REQUIREMENTS.
We are not allowed to touch requirements.
We can file bugs against requirements.

You as software tester NEVER write Requirements based on functionality. 
BA is providing the Requirements and we as software testers are validating those requirements.

That's the beauty of the role: as software tester you never have to invent requirements.
Happy testing!

**Comment by eszteradorjani** [comment]
Thank you for your thoughts! 
Indeed, as testers we are not required to write requirements, we base our tests on them. It also needs a different mindset, skillset and approach.

Since the application I have chosen for my exam lacked any documentation, requirements and specifications, I did take the liberty to create a few for the sake of learning and simulating a possible testing scenario. 
It helped in creating the test cases, learning to cover and link test cases to requirements, creating bug reports, discovering the possibilities of the test management tool, generating reports, and so much more. 

Doing this solo exercise has been a fantastic experience, helped immensely in deepening my previously accumulated knowledge.

**Comment by sebiboga** [comment]
alright then
let's close the bug 
have a great day ahead!
